// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package sql

import (
	"github.com/maxvoronov/otus-go-calendar/internal/logger"
)

// Injectors from wire.go:

func InitializeStorage() (*Storage, error) {
	databaseConfig := CreateConfigFromEnvironment()
	logrusLogger := logger.NewLogger()
	storage, err := NewStorage(databaseConfig, logrusLogger)
	if err != nil {
		return nil, err
	}
	return storage, nil
}
