version: "3.5"
services:
  api:
    container_name: otus-calendar-api
    build:
      context: ..
      dockerfile: deployments/images/golang/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ..:/app
    environment:
      HOTRELOAD_APP_CMD: "api-server"
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: password
      DB_NAME: calendar_db
    networks:
      - otus-network

  grpc:
    container_name: otus-calendar-grpc
    build:
      context: ..
      dockerfile: deployments/images/golang/Dockerfile
    ports:
      - "6565:6565"
    depends_on:
      - database
    volumes:
      - ..:/app
    environment:
      HOTRELOAD_APP_CMD: "grpc-server"
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: password
      DB_NAME: calendar_db
    networks:
      - otus-network

  database:
    container_name: otus-calendar-database
    image: postgres:12.1
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar_db
    networks:
      - otus-network

  migrations:
    container_name: otus-calendar-migrations
    build:
      context: ..
      dockerfile: deployments/images/migrator/Dockerfile
    depends_on:
      - database
    volumes:
      - ./migrations:/migrations
    networks:
      - otus-network
    entrypoint:
      - "/usr/local/bin/goose"
      - "postgres"
      - "postgres://root:password@database:5432/calendar_db?sslmode=disable"

networks:
  otus-network:
    name: otus-network