// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/maxvoronov/otus-go-calendar/internal/logger"
	"github.com/maxvoronov/otus-go-calendar/internal/messaging/amqp"
)

// Injectors from wire.go:

func InitializeNotificator() (*notificator, error) {
	messageBus, err := amqp.InitializeAmqp()
	if err != nil {
		return nil, err
	}
	logrusLogger := logger.NewLogger()
	mainNotificator := newNotificator(messageBus, logrusLogger)
	return mainNotificator, nil
}
