// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/event.proto

package eventproto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DateFrom             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_a660d132dceed454, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDateFrom() *timestamp.Timestamp {
	if m != nil {
		return m.DateFrom
	}
	return nil
}

func (m *Event) GetDateTo() *timestamp.Timestamp {
	if m != nil {
		return m.DateTo
	}
	return nil
}

type EventCreateRequest struct {
	Title                string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	DateFrom             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventCreateRequest) Reset()         { *m = EventCreateRequest{} }
func (m *EventCreateRequest) String() string { return proto.CompactTextString(m) }
func (*EventCreateRequest) ProtoMessage()    {}
func (*EventCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a660d132dceed454, []int{1}
}

func (m *EventCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventCreateRequest.Unmarshal(m, b)
}
func (m *EventCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventCreateRequest.Marshal(b, m, deterministic)
}
func (m *EventCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventCreateRequest.Merge(m, src)
}
func (m *EventCreateRequest) XXX_Size() int {
	return xxx_messageInfo_EventCreateRequest.Size(m)
}
func (m *EventCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventCreateRequest proto.InternalMessageInfo

func (m *EventCreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EventCreateRequest) GetDateFrom() *timestamp.Timestamp {
	if m != nil {
		return m.DateFrom
	}
	return nil
}

func (m *EventCreateRequest) GetDateTo() *timestamp.Timestamp {
	if m != nil {
		return m.DateTo
	}
	return nil
}

type EventCreateResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventCreateResponse) Reset()         { *m = EventCreateResponse{} }
func (m *EventCreateResponse) String() string { return proto.CompactTextString(m) }
func (*EventCreateResponse) ProtoMessage()    {}
func (*EventCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a660d132dceed454, []int{2}
}

func (m *EventCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventCreateResponse.Unmarshal(m, b)
}
func (m *EventCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventCreateResponse.Marshal(b, m, deterministic)
}
func (m *EventCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventCreateResponse.Merge(m, src)
}
func (m *EventCreateResponse) XXX_Size() int {
	return xxx_messageInfo_EventCreateResponse.Size(m)
}
func (m *EventCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventCreateResponse proto.InternalMessageInfo

func (m *EventCreateResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EventUpdateRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DateFrom             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventUpdateRequest) Reset()         { *m = EventUpdateRequest{} }
func (m *EventUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*EventUpdateRequest) ProtoMessage()    {}
func (*EventUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a660d132dceed454, []int{3}
}

func (m *EventUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventUpdateRequest.Unmarshal(m, b)
}
func (m *EventUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventUpdateRequest.Marshal(b, m, deterministic)
}
func (m *EventUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateRequest.Merge(m, src)
}
func (m *EventUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_EventUpdateRequest.Size(m)
}
func (m *EventUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateRequest proto.InternalMessageInfo

func (m *EventUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventUpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EventUpdateRequest) GetDateFrom() *timestamp.Timestamp {
	if m != nil {
		return m.DateFrom
	}
	return nil
}

func (m *EventUpdateRequest) GetDateTo() *timestamp.Timestamp {
	if m != nil {
		return m.DateTo
	}
	return nil
}

type EventUpdateResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventUpdateResponse) Reset()         { *m = EventUpdateResponse{} }
func (m *EventUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*EventUpdateResponse) ProtoMessage()    {}
func (*EventUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a660d132dceed454, []int{4}
}

func (m *EventUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventUpdateResponse.Unmarshal(m, b)
}
func (m *EventUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventUpdateResponse.Marshal(b, m, deterministic)
}
func (m *EventUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateResponse.Merge(m, src)
}
func (m *EventUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_EventUpdateResponse.Size(m)
}
func (m *EventUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateResponse proto.InternalMessageInfo

func (m *EventUpdateResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EventDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDeleteRequest) Reset()         { *m = EventDeleteRequest{} }
func (m *EventDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*EventDeleteRequest) ProtoMessage()    {}
func (*EventDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a660d132dceed454, []int{5}
}

func (m *EventDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDeleteRequest.Unmarshal(m, b)
}
func (m *EventDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDeleteRequest.Marshal(b, m, deterministic)
}
func (m *EventDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDeleteRequest.Merge(m, src)
}
func (m *EventDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_EventDeleteRequest.Size(m)
}
func (m *EventDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventDeleteRequest proto.InternalMessageInfo

func (m *EventDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EventDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDeleteResponse) Reset()         { *m = EventDeleteResponse{} }
func (m *EventDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*EventDeleteResponse) ProtoMessage()    {}
func (*EventDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a660d132dceed454, []int{6}
}

func (m *EventDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDeleteResponse.Unmarshal(m, b)
}
func (m *EventDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDeleteResponse.Marshal(b, m, deterministic)
}
func (m *EventDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDeleteResponse.Merge(m, src)
}
func (m *EventDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_EventDeleteResponse.Size(m)
}
func (m *EventDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventDeleteResponse proto.InternalMessageInfo

type EventGetListByPeriodRequest struct {
	DateFrom             *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventGetListByPeriodRequest) Reset()         { *m = EventGetListByPeriodRequest{} }
func (m *EventGetListByPeriodRequest) String() string { return proto.CompactTextString(m) }
func (*EventGetListByPeriodRequest) ProtoMessage()    {}
func (*EventGetListByPeriodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a660d132dceed454, []int{7}
}

func (m *EventGetListByPeriodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGetListByPeriodRequest.Unmarshal(m, b)
}
func (m *EventGetListByPeriodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGetListByPeriodRequest.Marshal(b, m, deterministic)
}
func (m *EventGetListByPeriodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGetListByPeriodRequest.Merge(m, src)
}
func (m *EventGetListByPeriodRequest) XXX_Size() int {
	return xxx_messageInfo_EventGetListByPeriodRequest.Size(m)
}
func (m *EventGetListByPeriodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGetListByPeriodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventGetListByPeriodRequest proto.InternalMessageInfo

func (m *EventGetListByPeriodRequest) GetDateFrom() *timestamp.Timestamp {
	if m != nil {
		return m.DateFrom
	}
	return nil
}

func (m *EventGetListByPeriodRequest) GetDateTo() *timestamp.Timestamp {
	if m != nil {
		return m.DateTo
	}
	return nil
}

type EventGetListByPeriodResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventGetListByPeriodResponse) Reset()         { *m = EventGetListByPeriodResponse{} }
func (m *EventGetListByPeriodResponse) String() string { return proto.CompactTextString(m) }
func (*EventGetListByPeriodResponse) ProtoMessage()    {}
func (*EventGetListByPeriodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a660d132dceed454, []int{8}
}

func (m *EventGetListByPeriodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventGetListByPeriodResponse.Unmarshal(m, b)
}
func (m *EventGetListByPeriodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventGetListByPeriodResponse.Marshal(b, m, deterministic)
}
func (m *EventGetListByPeriodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventGetListByPeriodResponse.Merge(m, src)
}
func (m *EventGetListByPeriodResponse) XXX_Size() int {
	return xxx_messageInfo_EventGetListByPeriodResponse.Size(m)
}
func (m *EventGetListByPeriodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventGetListByPeriodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventGetListByPeriodResponse proto.InternalMessageInfo

func (m *EventGetListByPeriodResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "events.Event")
	proto.RegisterType((*EventCreateRequest)(nil), "events.EventCreateRequest")
	proto.RegisterType((*EventCreateResponse)(nil), "events.EventCreateResponse")
	proto.RegisterType((*EventUpdateRequest)(nil), "events.EventUpdateRequest")
	proto.RegisterType((*EventUpdateResponse)(nil), "events.EventUpdateResponse")
	proto.RegisterType((*EventDeleteRequest)(nil), "events.EventDeleteRequest")
	proto.RegisterType((*EventDeleteResponse)(nil), "events.EventDeleteResponse")
	proto.RegisterType((*EventGetListByPeriodRequest)(nil), "events.EventGetListByPeriodRequest")
	proto.RegisterType((*EventGetListByPeriodResponse)(nil), "events.EventGetListByPeriodResponse")
}

func init() { proto.RegisterFile("grpc/proto/event.proto", fileDescriptor_a660d132dceed454) }

var fileDescriptor_a660d132dceed454 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0x66, 0xca, 0xa5, 0xf7, 0x72, 0xe0, 0xde, 0x9b, 0xcc, 0xfd, 0x49, 0x53, 0x4c, 0x24, 0x05,
	0x13, 0x56, 0x25, 0x81, 0x85, 0x89, 0x4b, 0x10, 0xdd, 0xb8, 0x30, 0x15, 0x37, 0x2e, 0x34, 0x48,
	0x0f, 0xa4, 0x09, 0x65, 0x6a, 0x3b, 0x90, 0xf8, 0x0c, 0xbe, 0x80, 0x89, 0x2f, 0xe0, 0x4b, 0xf8,
	0x6e, 0xa6, 0x33, 0x9d, 0xe8, 0x54, 0x50, 0x64, 0xe5, 0x0a, 0x66, 0xe6, 0x3b, 0xdf, 0xf9, 0xce,
	0xf7, 0x9d, 0xc2, 0xff, 0x69, 0x1c, 0x8d, 0xdb, 0x51, 0xcc, 0x38, 0x6b, 0xe3, 0x12, 0xe7, 0xdc,
	0x15, 0xff, 0xa9, 0x29, 0x0e, 0x89, 0xbd, 0x3b, 0x65, 0x6c, 0x3a, 0x43, 0x89, 0xb8, 0x5e, 0x4c,
	0xda, 0x3c, 0x08, 0x31, 0xe1, 0xa3, 0x30, 0x92, 0x40, 0xe7, 0x81, 0x40, 0x69, 0x90, 0x62, 0xe9,
	0x2f, 0x30, 0x02, 0xdf, 0x22, 0x75, 0xd2, 0x2a, 0x7b, 0x46, 0xe0, 0xd3, 0xbf, 0x50, 0xe2, 0x01,
	0x9f, 0xa1, 0x65, 0x88, 0x2b, 0x79, 0xa0, 0xfb, 0x50, 0xf6, 0x47, 0x1c, 0xaf, 0x26, 0x31, 0x0b,
	0xad, 0x62, 0x9d, 0xb4, 0x2a, 0x1d, 0xdb, 0x95, 0x4d, 0x5c, 0xd5, 0xc4, 0x1d, 0xaa, 0x26, 0xde,
	0x8f, 0x14, 0x7c, 0x14, 0xb3, 0x90, 0x76, 0xe1, 0xbb, 0x28, 0xe4, 0xcc, 0xfa, 0xf6, 0x61, 0x99,
	0x99, 0x42, 0x87, 0xcc, 0xb9, 0x27, 0x40, 0x85, 0xba, 0x7e, 0x8c, 0x23, 0x8e, 0x1e, 0xde, 0x2c,
	0x30, 0xe1, 0x2f, 0xd2, 0xc8, 0x5a, 0x69, 0xc6, 0x76, 0xd2, 0x8a, 0x1b, 0x4b, 0x3b, 0x80, 0x3f,
	0x9a, 0xb2, 0x24, 0x62, 0xf3, 0x04, 0x69, 0x03, 0x4a, 0xc2, 0x7a, 0x21, 0xad, 0xd2, 0xf9, 0xe9,
	0xca, 0x20, 0x5c, 0x81, 0xf5, 0xe4, 0x9b, 0xf3, 0xa8, 0xc6, 0x3a, 0x8f, 0xfc, 0x57, 0x63, 0x7d,
	0xc5, 0x04, 0xd4, 0x98, 0x4a, 0xe9, 0x67, 0xc6, 0x6c, 0x66, 0x53, 0x1e, 0xe2, 0x0c, 0xd7, 0x4e,
	0xe9, 0xfc, 0xcb, 0x3a, 0x28, 0x94, 0xec, 0xe0, 0xdc, 0x11, 0xa8, 0x89, 0xfb, 0x63, 0xe4, 0x27,
	0x41, 0xc2, 0x7b, 0xb7, 0xa7, 0x18, 0x07, 0xcc, 0x57, 0x34, 0x9a, 0x0d, 0x64, 0x3b, 0x1b, 0x8c,
	0x8d, 0x6d, 0x18, 0xc0, 0xce, 0x6a, 0x31, 0x99, 0x1f, 0x7b, 0x90, 0x7d, 0x71, 0x16, 0xa9, 0x17,
	0xdf, 0x1a, 0x92, 0x3d, 0x76, 0x9e, 0x0c, 0xa8, 0x8a, 0x9b, 0x33, 0x8c, 0x97, 0xc1, 0x18, 0x69,
	0x1f, 0x4c, 0xb9, 0x40, 0xd4, 0xd6, 0x2a, 0xb4, 0x7d, 0xb7, 0x6b, 0x2b, 0xdf, 0x32, 0xa3, 0x0a,
	0x29, 0x89, 0x8c, 0x27, 0x47, 0xa2, 0x6d, 0x57, 0x8e, 0x44, 0xcf, 0x53, 0x92, 0xc8, 0x04, 0x72,
	0x24, 0x5a, 0x78, 0x39, 0x92, 0x5c, 0x64, 0x05, 0x7a, 0x09, 0xbf, 0x73, 0x0e, 0xd1, 0x86, 0x56,
	0xb1, 0x3a, 0x4c, 0xbb, 0xf9, 0x3e, 0x48, 0xf1, 0xf7, 0xaa, 0x17, 0x20, 0x80, 0x32, 0x29, 0x53,
	0xfc, 0x74, 0x9f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x4c, 0x5b, 0x74, 0x05, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	Create(ctx context.Context, in *EventCreateRequest, opts ...grpc.CallOption) (*EventCreateResponse, error)
	Update(ctx context.Context, in *EventUpdateRequest, opts ...grpc.CallOption) (*EventUpdateResponse, error)
	Delete(ctx context.Context, in *EventDeleteRequest, opts ...grpc.CallOption) (*EventDeleteResponse, error)
	GetListByPeriod(ctx context.Context, in *EventGetListByPeriodRequest, opts ...grpc.CallOption) (*EventGetListByPeriodResponse, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) Create(ctx context.Context, in *EventCreateRequest, opts ...grpc.CallOption) (*EventCreateResponse, error) {
	out := new(EventCreateResponse)
	err := c.cc.Invoke(ctx, "/events.EventService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Update(ctx context.Context, in *EventUpdateRequest, opts ...grpc.CallOption) (*EventUpdateResponse, error) {
	out := new(EventUpdateResponse)
	err := c.cc.Invoke(ctx, "/events.EventService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) Delete(ctx context.Context, in *EventDeleteRequest, opts ...grpc.CallOption) (*EventDeleteResponse, error) {
	out := new(EventDeleteResponse)
	err := c.cc.Invoke(ctx, "/events.EventService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetListByPeriod(ctx context.Context, in *EventGetListByPeriodRequest, opts ...grpc.CallOption) (*EventGetListByPeriodResponse, error) {
	out := new(EventGetListByPeriodResponse)
	err := c.cc.Invoke(ctx, "/events.EventService/GetListByPeriod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	Create(context.Context, *EventCreateRequest) (*EventCreateResponse, error)
	Update(context.Context, *EventUpdateRequest) (*EventUpdateResponse, error)
	Delete(context.Context, *EventDeleteRequest) (*EventDeleteResponse, error)
	GetListByPeriod(context.Context, *EventGetListByPeriodRequest) (*EventGetListByPeriodResponse, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) Create(ctx context.Context, req *EventCreateRequest) (*EventCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedEventServiceServer) Update(ctx context.Context, req *EventUpdateRequest) (*EventUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedEventServiceServer) Delete(ctx context.Context, req *EventDeleteRequest) (*EventDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedEventServiceServer) GetListByPeriod(ctx context.Context, req *EventGetListByPeriodRequest) (*EventGetListByPeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListByPeriod not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/events.EventService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Create(ctx, req.(*EventCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/events.EventService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Update(ctx, req.(*EventUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/events.EventService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).Delete(ctx, req.(*EventDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetListByPeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventGetListByPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetListByPeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/events.EventService/GetListByPeriod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetListByPeriod(ctx, req.(*EventGetListByPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "events.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EventService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EventService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EventService_Delete_Handler,
		},
		{
			MethodName: "GetListByPeriod",
			Handler:    _EventService_GetListByPeriod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/event.proto",
}
